name: tkedit # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: edit python files # 79 char long summary
description: |
    This is a python text editor with syntax highlighting

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    tkedit:
        command: tkedit

parts:
    tkedit:
        source: /home/dvlv/tkedit
        plugin: python3
        python-version: python3
        stage-packages: [python3-tk]
